language: node_js
sudo: false
node_js:
  - "10"

install:
  - npm ci

script:
  - npm run lint
  - npm run test
  - npm run build
  - echo 'BUILD SUCCESS'
  - ls

before_deploy:
  - npx copy CHANGELOG.md package.json README.md LICENSE ./dist
  - cd ./dist
  - ls

deploy:
  - provider: npm
    edge: true
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master

